# Generated by Django 5.2 on 2025-05-08 14:51

import django.db.models.deletion
import django.utils.timezone
import game.models.company_game
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetTransaction',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('transactionType', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=5)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGame',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('updated_property', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company_id', models.UUIDField()),
                ('description', models.TextField()),
                ('is_playable', models.BooleanField(default=True)),
                ('mechanics', models.JSONField(default=game.models.company_game.CompanyGame.game_mechanics_default, verbose_name='Game Mechanics')),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('digits', models.IntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BetItem',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('straightAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rumbleAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bet_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_items', to='game.bettransaction')),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_items', to='game.combination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CombinationLimit',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('updated_property', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('straight_limit', models.IntegerField()),
                ('rumble_limit', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='game.combination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrawSchedule',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('updated_property', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='DrawSchedule', max_length=255)),
                ('cutoff_time', models.BigIntegerField()),
                ('open_time', models.BigIntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('company_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draw_schedules', to='game.companygame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='companygame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_games', to='game.game'),
        ),
        migrations.CreateModel(
            name='GameSchedule',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('updated_property', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.BigIntegerField()),
                ('allow_advanced', models.BooleanField(default=True)),
                ('status', models.IntegerField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('win_amount', models.IntegerField(default=0)),
                ('straight_limit', models.IntegerField(default=0)),
                ('rumble_limit', models.IntegerField(default=0)),
                ('scheduleName', models.CharField(max_length=255)),
                ('cutoff_time', models.BigIntegerField()),
                ('open_time', models.BigIntegerField()),
                ('draw_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='game.drawschedule')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='game.companygame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bettransaction',
            name='game_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_transactions', to='game.gameschedule'),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('updated_property', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.combination')),
                ('game_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.gameschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('win_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rumble_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bet_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='game.betitem')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='game.result')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
