# Generated by Django 5.2 on 2025-05-08 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldoutCombination',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(null=True)),
                ('updated_by', models.BigIntegerField(null=True)),
                ('updated_property', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldouts', to='game.combination')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
