# Generated by Django 5.2 on 2025-05-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawschedule',
            old_name='cutoff_time',
            new_name='cutoff_end',
        ),
        migrations.RenameField(
            model_name='drawschedule',
            old_name='open_time',
            new_name='cutoff_start',
        ),
    ]
