# Generated by Django 5.2 on 2025-05-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_cutoff_time_drawschedule_cutoff_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameschedule',
            name='cutoff_time',
        ),
        migrations.RemoveField(
            model_name='gameschedule',
            name='open_time',
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='cutoff_end',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='cutoff_start',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
