# Generated by Django 5.2 on 2025-05-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_soldoutcombination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameschedule',
            old_name='game',
            new_name='company_game',
        ),
    ]
