# Generated by Django 5.2 on 2025-05-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_result_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combination',
            name='value',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
