# Generated by Django 5.2 on 2025-05-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_combination_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='rumble_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='winner',
            name='win_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
